name: build
on:
  pull_request:
  push:
    branches: [ rolling ]
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: ['iron', 'jazzy', 'rolling']
    container:
      image: ros:${{ matrix.distro }}-ros-base
      options: --privileged
      volumes:
        - /dev/kmsg:/dev/kmsg
        - /sys/devices/system/:/sys/devices/system/
    timeout-minutes: 30
    steps:
    - name: Deps
      run: |
        apt update && apt install -y curl
    - uses: actions/checkout@v4
    - name: cpufreq_denemeleri
      run: |
        apt update
        apt install cpufrequtils tree linux-tools-common linux-cloud-tools-azure linux-tools-azure -y
        lscpu
        sysctl kernel.dmesg_restrict=0
        dmesg | grep -i cpu
        cpufreq-info
        tree /sys/devices/system/cpu/
        cat /sys/devices/system/cpu/cpuidle/available_governors
        cpupower frequency-info
        cpufreq-set -g performance
