name: build
on:
  pull_request:
  push:
    branches: [ rolling ]
  workflow_dispatch:
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 5 * * *'
defaults:
  run:
    shell: bash
jobs:
  build_and_test:
    name: no_regrets_${{ matrix.BUILD_TYPE }}_${{ matrix.ROS_DISTRO }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Rolling (source)
          - ROS_DISTRO: rolling
            BUILD_TYPE: source
          # Jazzy (binary)
          - ROS_DISTRO: jazzy
            BUILD_TYPE: binary
          # Iron (binary)
          - ROS_DISTRO: iron
            BUILD_TYPE: binary
    env:
      ROS2_REPOS_FILE_URL: 'https://raw.githubusercontent.com/ros2/ros2/${{ matrix.ROS_DISTRO }}/ros2.repos'
      RMW_MIDDLEWARE_TEST_PACKAGES: 'test_rclcpp rcl'
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.BUILD_TYPE == 'binary' && format('ros:{0}-ros-base', matrix.ROS_DISTRO) || 'ubuntu:noble' }}
    steps:
    - uses: ros-tooling/setup-ros@v0.7
      # if: ${{ matrix.BUILD_TYPE == 'source' }}
      with:
        use-ros2-testing: true
        required-ros-distributions: ${{ matrix.ROS_DISTRO }}
    - name: elma
      run: |
        /ros_entrypoint.sh rosinstall_generator test_rclcpp --rosdistro ${{ matrix.ROS_DISTRO }} --deps-only --deps --upstream-development > /tmp/deps.repos
        cat /tmp/deps.repos
